version: '3.4'  # Specifies the version of the Docker Compose file format

services:
  weaviate:
    command:
      - --host
      - 0.0.0.0  # Binds Weaviate to all network interfaces
      - --port
      - '8080'  # Sets the port for Weaviate
      - --scheme
      - http  # Specifies the scheme (protocol) as HTTP
    image: semitechnologies/weaviate:1.22.5  # Specifies the Weaviate image and version
    ports:
      - 8080:8080  # Maps the host's port 8080 to the container's port 8080 (HTTP)
      - 50051:50051  # Maps the host's port 50051 to the container's port 50051 (gRPC)
    restart: on-failure  # Restart policy - restarts the container on failure, with a maximum of 0 retries
    environment:
      QUERY_DEFAULTS_LIMIT: 25  # Sets the default limit for queries
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'  # Enables anonymous access to Weaviate
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'  # Sets the data path for persistence
      DEFAULT_VECTORIZER_MODULE: 'multi2vec-bind'  # Sets the default vectorizer module
      ENABLE_MODULES: 'multi2vec-bind'  # Enables the multi2vec-bind module
      BIND_INFERENCE_API: 'http://multi2vec-bind:8080'  # Specifies the inference API for the bind module
      CLUSTER_HOSTNAME: 'node1'  # Hostname for the cluster node

  multi2vec-bind:
    mem_limit: 12G  # Limits memory usage to 12GB
    image: semitechnologies/multi2vec-bind:imagebind  # Specifies the multi2vec-bind image
    environment:
      ENABLE_CUDA: '0'  # Disables CUDA, useful for environments without GPU support
